version: '3.1'

services:

      
### torrent part ###

  test:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
 
networks:
  zabbix:
    driver: bridge
