version: '3.1'

services:

### zabbix part 
  postgres-server:
    restart: always
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: n6MavX5Dc2%^-5J
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    networks:
      - zabbix

  zabbix-server:
    restart: always
    image: zabbix/zabbix-server-pgsql:5.0-alpine-latest
    environment:
      # ZBX_TLSCAFILE: Gestion_Systemes_Telecom_root_ca.crt
      # ZBX_TLSCERTFILE: zabbix_server.crt
      # ZBX_TLSKEYFILE: zabbix_server.key
      POSTGRES_PASSWORD: n6MavX5Dc2%^-5J
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"
    depends_on:
      - postgres-server
    networks:                                                
      - zabbix
    # volumes:
    #    - c:\zabbix_conf\:/var/lib/zabbix/enc
      

  zabbix-web:
     restart: always
     image: zabbix/zabbix-web-nginx-pgsql:5.0-alpine-latest
     environment:
       ZBX_SERVER_HOST: zabbix-server
       ZBX_SERVER_PORT: 10051
       DB_SERVER_HOST: postgres-server
       DB_SERVER_PORT: 5432
       POSTGRES_USER: zabbix
       POSTGRES_PASSWORD: n6MavX5Dc2%^-5J
       PHP_TZ: Europe/Paris
     depends_on:
      - postgres-server
      - zabbix-server 
     networks:
      - zabbix
     ports:
       - "80:8080"
      
networks:
  zabbix:
    driver: bridge